version: '3'

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    image: minelytics-notebook
    volumes:
      - .:/home/jovyan
    ports:
      - "8888:8888"
    command: "start-notebook.sh"
